version: "3.5"
services:
  nethermind:
    build:
      context: .
      args:
        UPSTREAM_VERSION: 1.13.4
    image: "nethermind.nethermind-ropsten.public.dappnode.eth:1.0.9"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - "data:/data"
    environment:
      MODE: normal
      OVERRIDE_TTD: 50000000000000000
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: 0.0.0.0
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_NETWORKCONFIG_DISCOVERYPORT: 30390
      NETHERMIND_NETWORKCONFIG_P2PPORT: 30390
      LOG: DEBUG
      EXTRA_OPTS: ""
    ports:
      - "30390:30390/udp"
      - "30390:30390/tcp"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 16384M
volumes:
  data: {}
